apiVersion: v1
kind: Service
metadata:
  name: {{ include "apps-helm.fullname" . }}-backend
  labels:
    {{- include "apps-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "apps-helm.selectorLabels" . | nindent 4 }}
