{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apps-helm.fullname" . }}-frontend
spec:
  type: ClusterIP
  selector:
    app: {{ include "apps-helm.name" . }}-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
{{- end -}}